gear-tech/gear-js

- ansible/tasks/nginx/proxy.conf
minor fix
remove unused strings
> minor-nginx-conf-fix

- ansible/tasks/frontend/frontend.yaml
add ansible task to remove old front files
> add ansible task to remove old front files

- frontend/src/consts.ts
- frontend/yarn.lock
Fixes # .
- Fix merge conflict
> fix: merge conflict

- README.md
- api/README.md
- api/examples/index.ts
- api/src/Events.ts
Add # .
- Subscribtion to new blocks
- Update readme
> add: subscription to new blocks

- api/package-lock.json
- api/package.json
- api/src/interfaces/gear-api.ts
Fixes # .
- Fix provider type
- update version
> Fix provider type

- api/.gitignore
- api/.npmignore
- api/package-lock.json
- api/package.json
- api/tsconfig.json
Fixes # .
- fix installing types
- add prepare script
- remove postinstall script
- update package version
@EugenWay
> Fix installing gear-js/api using npm

- website/backend/src/ws-rpc/ws-rpc.handler.ts
- website/backend/src/ws-rpc/ws-rpc.methods.ts
- website/backend/static/index.html
Add # .
- Unsubcribe method for new blocks and events
> Unsubcribe method

- website/backend/.env.example
- website/backend/src/gear-node/gear-node.service.ts
Add environment variable DEBUG.
For correct launch backend in development mode set the variable value to 1
> Add env variable for running in debug mode

- api/README.md
- api/package-lock.json
- api/package.json
- api/src/Events.ts
- api/src/Program.ts
- api/src/index.ts
- api/src/interfaces/augment-api-rpc.ts
- api/src/interfaces/message.ts
- api/tsconfig.json
Fixes # .
- Add events unsubsribing
> Add unsubscribing from events

- api/.npmignore
- api/package-lock.json
- api/package.json
- api/src/CreateType.ts
- api/src/interfaces/index.ts
- api/tsconfig.json
> Fix decoding string (api)

- api/package-lock.json
- api/package.json
- api/src/Program.ts
Fixes # .
- Rename program_id -> programId
> Fix getting uploaded program id

- api/.npmignore
- api/README.md
- api/package-lock.json
- api/package.json
- api/src/Keyring.ts
Add
- Sign message using GearKeyring.sign method
- Check signature using GearKeyring.checkSign method
> Add sign messages

- website/frontend/src/api/initApi.ts
- website/frontend/src/components/blocks/Keyring/Keyring.tsx
- website/frontend/src/consts.ts
- add connection address env var
- add address_raw to localStorage
> Add to localStorage addressRad, add to env api connect adress

- api/README.md
- api/package-lock.json
- api/package.json
- api/src/GearApi.ts
For check what the event is use: 
```javascript
gearApi.allEvents((events) => {
events
.filter(({ event }) => gearApi.events.gear.InitMessageEnqueued.is(event))
.forEach(({ event: { data } }) => {
console.log(data.toHuman())
});
events
.filter(({ event }) => gearApi.events.balances.Transfer.is(event))
.forEach(({ event: { data } }) => {
console.log(data.toHuman())
});
```
> Add check what event is (api)

- api/package-lock.json
- api/package.json
- api/src/Message.ts
- api/src/Program.ts
Current version @gear-js/lib: `0.4.4`
> Await isFinalized status of transactions (api)

- api/package-lock.json
- api/package.json
- api/src/WasmMeta.ts
Add new callbacks to getWasmMetadata
> Fix getWasmMetadata

- website/frontend/package-lock.json
- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/blocks/Keyring/Keyring.tsx
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
- website/frontend/src/components/blocks/Wallet/Wallet.tsx
> Release fixes

- website/frontend/src/components/pages/Programs/Programs.tsx
- website/frontend/src/components/pages/Programs/children/BlocksList/BlocksList.scss
- website/frontend/src/components/pages/Programs/children/BlocksList/BlocksList.tsx
> Fix: block timer issues

- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
> Delete useless transfer alert

- package-lock.json
- website/frontend/package.json
- website/frontend/src/components/blocks/MetaForm/MetaForm.tsx
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
- website/frontend/src/components/pages/Programs/children/Message/children/MessageForm/MessageForm.tsx
- website/frontend/src/consts.ts
- website/frontend/src/services/ApiService.tsx
- website/frontend/src/types/program.ts
Fixes # .
input -> handle_input
output -> handle_output
> Replace metadata props

- api/api/package-lock.json
- api/api/package.json
- api/api/src/CreateType.ts
Fixes # .
Change using portable registry to create types
https://github.com/polkadot-js/api/pull/4172
> GenericPortableRegistry -> PortableRegistry

- website/frontend/package.json
- website/frontend/src/components/pages/Programs/children/All/All.tsx
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
- website/frontend/src/store/actions/actions.ts
- website/frontend/src/store/reducers/ProgramReducer.ts
- website/frontend/src/types/program.ts
> added new logic for the search

- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.scss
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
- website/frontend/src/components/blocks/ProgramDetails/Schema.ts
- website/frontend/src/services/ApiService.tsx
- website/frontend/src/types/program.ts
> Add new field with name

- website/frontend/src/components/pages/Programs/children/All/All.module.scss
- website/frontend/src/helpers.ts
> fix string shortering

- website/backend/package.json
- website/frontend/package.json
> Bump @gear-js to v0.7.2

- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.scss
- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
- website/frontend/src/consts.ts
> Gas adjustments

- website/frontend/src/components/App/App.tsx
- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/pages/Program/Program.scss
- website/frontend/src/components/pages/Program/Program.tsx
- website/frontend/src/components/pages/Programs/children/UserProgram/UserProgram.module.scss
- website/frontend/src/components/pages/Programs/children/UserProgram/UserProgram.tsx
- website/frontend/src/routes.ts
- website/frontend/src/types/program.ts
> Add program page

- api/api/package-lock.json
- api/api/package.json
- api/api/src/GearApi.ts
- api/api/src/Program.ts
- api/api/src/State.ts
- api/api/src/WasmMeta.ts
- api/api/src/errors/state.errors.ts
- api/api/src/index.ts
- api/api/src/interfaces/gear-api.ts
- api/api/src/interfaces/metadata.ts
- api/api/src/interfaces/program.ts
```javascript
import { GearApi } from '@gear-js/api';
import * as fs from 'fs';
const metaFile = fs.readFileSync('path/to/program.meta.wasm');
const api = await GearApi.create();
const state = await api.programState.read(
'0x668e0845f08e7387db88472886b63d01e92f8483c9435343e864dec933282afb', // programId
metaFile
);
console.log(state.toHuman());
```
https://github.com/gear-tech/gear/pull/410
> Read program state

- api/api/package-lock.json
- api/api/package.json
- api/api/src/Balance.ts
- api/examples/src/balance.ts
`version 0.8.3`
```javascript
const api = await GearApi.create();
const freeBalance = await api.balance.findOut(userPublicKey);
console.log(freeBalance.toHuman()); // out: 1.1529 MUnit
```
> Add create type balance for free balance

- website/frontend/src/components/blocks/Header/Header.scss
- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
Also: 
- Removed unnecessary code 
- Changed the amount which you can get from Alice for your test balance in the dev mode
> Add possibility remove and copy node address

- .github/workflows/CD.yml
- website/backend/tsconfig.json
add skipLibCheck to tsconfig.json
> Fix build backend

- api/api/package-lock.json
- api/api/package.json
- api/api/src/CreateType.ts
Fix:
- replace custom namespaces in createType
> Replace namespaces in createType

- api/api/package-lock.json
- api/api/package.json
- api/api/src/WasmMeta.ts
> Wasm exports

- website/frontend/src/components/pages/Program/Program.tsx
Fixed error that appears on the Program page when meta is empty.
> Fix error when meta is empty

- api/api/package-lock.json
- api/api/package.json
- api/api/src/CreateType.ts
`0.8.7`
Fix check if payload unspecified. 
!payload -> payload ===undefiend
> Fix unspecified payload

- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.scss
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
Added new styles for the better adaptive
Fixed some thing that trigger Warning in the console
> Improve adaptive and fix warning

- api/api/package-lock.json
- api/api/package.json
- api/api/src/DebugMode.ts
`current lib version is 0.8.9`
> Rename debug pallet

- website/frontend/src/components/blocks/ProgramDetails/Schema.ts
Changed max value for a program name. Now it's 50 symbols.
> Change max value for a program name

- website/frontend/src/components/pages/Programs/children/Message/Message.tsx
Just removed the calling of red alert
> removed error alert duplication

- website/frontend/src/components/Pagination/Pagination.tsx
- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/pages/Notifications/NotificationsPage.tsx
- website/frontend/src/components/pages/Programs/children/All/All.tsx
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
- website/frontend/src/features/BlockList/BlockListAllUploaded.tsx
Now current page saves like GET-parameter, so we can copy an URL and paste it anywhere and there's no problem. 
Also no problem when we go back from a program page.
> Save current page like GET-parameter in the pagination

- api/api/package-lock.json
- api/api/package.json
- api/api/src/State.ts
- api/api/src/WasmMeta.ts
> Add optional showing gr_debug

- website/frontend/src/components/blocks/Modal/Modal.scss
- website/frontend/src/components/blocks/Modal/Modal.tsx
- website/frontend/src/components/blocks/PageHeader/PageHeader.tsx
- website/frontend/src/components/blocks/Wallet/Wallet.scss
- website/frontend/src/components/blocks/Wallet/Wallet.tsx
Added Wallet component to the header of the popup.
Changed some styles, in particular, added variables with color.
> Add wallet to the popup

- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
> Fix balance transfer

- website/frontend/package-lock.json
- website/frontend/src/components/App/App.scss
- website/frontend/src/components/LoadingPopup/LoadingPopup.scss
Resolve # .
- change css positions
> Resolve overlay layout bug

- website/frontend/src/components/blocks/Wallet/Wallet.tsx
> Add addressRaw

- website/frontend/package.json
> Bump @gear-js/api -> 0.8.12

- api/api/package-lock.json
- api/api/package.json
- api/api/src/Message.ts
- api/api/src/MessageReply.ts
- api/api/src/Program.ts
- api/api/src/utils.ts
> Fix payload toHex

- api/api/package-lock.json
- api/api/package.json
- api/api/src/Message.ts
- api/api/src/MessageReply.ts
- api/api/src/Program.ts
- api/api/src/utils.ts
> Fix create payload

- api/api/package-lock.json
- api/api/package.json
- api/api/src/utils.ts
> Fix encode payload

- website/frontend/src/components/blocks/ProgramSwitch/ProgramSwitch.tsx
Resolves # .
Remove unnecessary alert when transfer balance is succeeded 
> Remove manual transfer balance alert

- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
Someone deleted function that reset form. I've returned it
> Return function that reset form

- website/frontend/src/components/blocks/Header/Header.tsx
Added import with the necessary function: **saveAs**
> Add import with the necessary function

- website/backend/Dockerfile
- website/frontend/Dockerfile
- Build frontend to be static.
- Serve with Nginx.
> Update frontend Dockerfile

- website/frontend/src/components/blocks/AccountList/AccountList.tsx
- website/frontend/src/components/blocks/Wallet/Wallet.tsx
- add account select modal hiding
- code improvements
> add account select modal hiding and code improvements

- api/api/package-lock.json
- api/api/package.json
- api/api/src/Events.ts
- api/examples/src/balance.ts
`version 0.8.17`
Add event to listen to balance change
[Usage](https://github.com/gear-tech/gear-js/blob/do-balance-change/api/examples/src/balance.ts)
> Listen to balance change

- website/frontend/package.json
> Fix: bigNum bug

- api/api/package-lock.json
- api/api/package.json
- api/api/src/WasmMeta.ts
> gr_program_id syscall

- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
Changed icon for the delete program button in the uploading process
Deleted unnecessary code
> Change icon and delete unnecessary code

- .github/workflows/CI.yml
- .github/workflows/prod.CD-frontend.yaml
- .github/workflows/staging.CD-frontend.yaml
- website/frontend/craco.config.js
- update RRT env name
- add frontend env assertions
> Check env variables on frontend

- website/frontend/src/components/Pagination/Pagination.tsx
There's a fixed problem with pagination logic for the different components: messages, user programs, all programs.
> Fix pagination

- website/frontend/src/components/blocks/SearchForm/SearchForm.tsx
- website/frontend/src/components/pages/Messages/Messages.tsx
- website/frontend/src/components/pages/Notifications/NotificationsPage.tsx
- website/frontend/src/components/pages/Programs/children/All/All.tsx
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
Added a new prop with a text for the placeholder in the search input.
> Fix placeholder in the search

- website/api-gateway/src/interfaces/general.ts
- website/api-gateway/src/interfaces/program.ts
- website/backend/src/gear-node/events.ts
- website/backend/src/programs/entities/program.entity.ts
- website/backend/src/programs/programs.service.ts
- website/data-storage/src/consumer/consumer.service.ts
- website/data-storage/src/interfaces/general.ts
- website/data-storage/src/interfaces/message.ts
- website/data-storage/src/interfaces/program.ts
- website/data-storage/src/messages/entities/message.entity.ts
- website/data-storage/src/messages/messages.service.ts
- website/data-storage/src/metadata/metadata.service.ts
- website/data-storage/src/programs/entities/program.entity.ts
- website/data-storage/src/programs/programs.service.ts
Parameter `chain` removed from everywhere as redundant.
> contracts: remove parameter `chain`

- HEADER-GPL3
- website/frontend/src/components/blocks/Documents/DocumentFooter.tsx
- website/frontend/src/components/blocks/Footer/Footer.tsx
- website/frontend/src/features/Editor/EditorPage/EditorPage.tsx
> gardening: bump copyright year

- website/frontend/craco.config.js
- website/frontend/package.json
- yarn.lock
> add buffer

- website/frontend/src/components/blocks/Wallet/Wallet.tsx
Resolves # .
Bugfix: add setTimeout until Windows object exists
> [Bugfix] Add fetch accounts delay

- api/.gitignore
- api/package-lock.json
Restore package-lock in api because `npm ci` command doesn't work without it
> Restore package-lock.json in api dir

- api/src/Events.ts
These changes add missing letters.
> Typo in API

- website/frontend/src/components/pages/Message/Message.tsx
This pull request fixed checking meta for the payload on the message page
> Change checking meta

- website/frontend/src/components/pages/SendMessage/SendMessage.tsx
Changed the method that get meta from the localDB
> Get meta from localDB

- website/frontend/src/components/Pagination/Pagination.tsx
- website/frontend/src/components/pages/Messages/Messages.tsx
- website/frontend/src/components/pages/Programs/children/All/All.tsx
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
> Rewrite pagination logic

- website/frontend/src/components/pages/Explorer/EventsList/children/EventItem/children/Body/children/Content/Content.tsx
- website/frontend/src/components/pages/Explorer/EventsList/children/EventItem/children/Body/children/LogContent/LogContent.tsx
- website/frontend/src/components/pages/Program/Program.tsx
- website/frontend/src/components/pages/SendMessage/children/MessageForm/MessageForm.tsx
- website/frontend/src/helpers.ts
Fix some properties not decoding properly.
> Fix events formatting

- website/frontend/src/components/blocks/Header/children/Menu/Menu.module.scss
- website/frontend/src/components/blocks/Header/children/Menu/Menu.tsx
Fixes incorrect sizes of header menu items leading to wrong hover cursor.
> Fix header links hover

- website/frontend/package.json
- website/frontend/src/consts.ts
- website/frontend/src/services/ApiService.tsx
- yarn.lock
> Refactor uploadProgram and SendMessageToProgram methods

- .github/workflows/CD-wasm-compiler.yaml
- ansible/tasks/wasm-compiler/database.yaml
- ansible/tasks/wasm-compiler/wasm-compiler.yaml
- website/test-balance/package.json
- website/test-balance/src/gear.ts
- yarn.lock
- Fix wasm-compiler service deploy
- Bump @gear-js/api in test-balance service
> Fix wasm-compiler service deploy

- website/data-storage/src/messages/messages.service.ts
- website/data-storage/src/programs/programs.service.ts
- website/interfaces/src/api-requests.ts
Now a user could see their programs filtered in the same manner as in "All Programs".
> Search "My Programs" as well

- website/api-gateway/src/api-gateway/api-gateway.service.ts
- website/data-storage/src/consumer/consumer.controller.ts
- website/data-storage/src/consumer/consumer.service.ts
- website/data-storage/src/messages/messages.service.ts
- website/data-storage/src/programs/programs.service.ts
- website/data-storage/src/utils.ts
- website/frontend/src/components/pages/Programs/children/Recent/Recent.tsx
- website/frontend/src/types/common.ts
- website/interfaces/src/api-requests.ts
- Refactor getting user programs
- Refactor getting search params
> Refactor getting user programs

- api/README.md
- api/package-lock.json
- api/package.json
- api/src/Blocks.ts
- api/test/GearApi.test.js
- Add method to get timestamp of particular block
- One method to get block by blockHash or blockNumber
- Bump version to `0.11.3`
> Get block timestamp

- website/frontend/src/components/pages/Messages/Messages.tsx
Add new parameter to the request
> Fix message search

- website/frontend/src/components/blocks/Loader/Loader.module.scss
> Tweak cogs

- website/events-listener/src/index.ts
- website/events-listener/src/lifecycle.ts
After this PR the main event loop in the Event Listener becomes a loop.
Also see #326.
> Event Listener now reconnects whenever the connection is lost

- package.json
- website/frontend/package.json
- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
- website/frontend/src/components/blocks/ProgramDetails/types.ts
- website/frontend/src/components/pages/SendMessage/children/MessageForm/MessageForm.tsx
- website/frontend/src/components/pages/SendMessage/children/MessageForm/types.ts
- website/frontend/src/services/ApiService.tsx
- yarn.lock
- Update on the page with sending message
- Add on the page with upload program form
- Update API to 0.12.0
> Update calculate gas logic

- website/frontend/src/components/App/App.tsx
- website/frontend/src/components/pages/Programs/children/BlocksList/BlocksList.scss
- website/frontend/src/components/pages/Programs/children/BlocksList/BlocksList.tsx
- website/frontend/src/types/block.ts
Adds timestamp display for blocks in block list.
> Add block timestamp

- website/frontend/src/components/blocks/ProgramDetails/ProgramDetails.tsx
Set default value for Initial parameters on the page with uploading program
> Set default value for Initial parameters

- .github/workflows/CI-CD-All-dockers-k8s.yml
- k8s/api-gateway/api-gateway.yaml
- k8s/data-storage/data-storage.yaml
- k8s/events-listeners/events-listener-rpc-testnet.yaml
- k8s/events-listeners/events-listener-workshop-node.yaml
- k8s/frontend-nginx/frontend-nginx.yaml
- k8s/test-balance/test-balance-workshop-node.yaml
changes names of containers and add in workflow previous wait run
> change workflow and change names of containers

- website/frontend/src/services/ApiService.tsx
Changes type of gas limit and value inputs of submitted program/message to string.
> Change program/message gas limit and value type

- api/package-lock.json
- api/package.json
- api/src/GearApi.ts
- api/test/ExtrinsicError.test.js
- api/test/GearApi.test.js
> Add getting ExtrinsicFailed error docs

- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
Resolved issue [394](https://github.com/gear-tech/gear-js/issues/394)
> Fix form with upload program

- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- website/frontend/src/helpers.ts
- Fix program payload not sending
- Fix type of calculated gas limit
> Fix payload submit on program upload

- ansible/tasks/api-gateway/docker-compose.yaml
- ansible/tasks/data-storage/docker-compose.yaml
- ansible/tasks/events-listener/docker-compose.yaml
- ansible/tasks/frontend/docker-compose.yaml
- ansible/tasks/test-balance/docker-compose.yaml
change url for prod docker images
> change url in repo

- website/frontend/public/index.html
- add proper page title for SEO
> update page title for SEO

- api/package-lock.json
- api/package.json
- api/src/MessageReply.ts
- Add extends GearTransaction to `MessageReply` class
- bump lib version to `0.14.3`
> SignAndSend reply message

- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/types.ts
Removed types from the query if there's no meta.
> Fix upload program

- website/frontend/src/components/blocks/Header/Header.module.scss
- website/frontend/src/components/blocks/Header/children/Menu/Menu.module.scss
- website/frontend/src/components/blocks/Header/children/Menu/Menu.tsx
- Add style for the active menu item
- Remove old style
> Add active menu item highlight

- api/README.md
- api/package-lock.json
- api/package.json
- api/src/Message.ts
- api/src/MessageReply.ts
- api/src/Program.ts
- Rename `api.reply.submitReply` -> `api.reply.submit`
- Rename `toId` parameter of `reply.submit` method to `replyToId`
- Examples for `program.submit` and `message.submit` methods
- Return types for `message.submit` and `reply.submit` methods
- Return submitted result from `program.submit` method
- @polkadot/api to 7.12.1
- rxjs ot 7.5.5
<hr>
> Refactor messageReply

- api/src/GasSpent.ts
- api/src/default/rpc.json
- api/src/interfaces/augment-api-rpc.ts
- api/test/ProgramsInteract.test.js
Update gasSpent rpc calls following https://github.com/gear-tech/gear/pull/727
> Update gasSpent rpc call

- website/frontend/package.json
- website/frontend/src/helpers.ts
- yarn.lock
> Add value on gasSpent submit

- website/frontend/src/common/components/BackButton/BackButton.tsx
- website/frontend/src/common/components/Button/Button.module.scss
- website/frontend/src/common/components/Button/Button.test.tsx
- website/frontend/src/common/components/Button/Button.tsx
- website/frontend/src/common/components/Button/types.tsx
- website/frontend/src/components/blocks/Header/children/Sidebar/children/Header/Header.tsx
- website/frontend/src/components/blocks/Header/children/Sidebar/children/Nodes/Section/Node/Node.tsx
- website/frontend/src/components/pages/Programs/children/Upload/children/CodeModal/CodeModal.tsx
- website/frontend/src/components/pages/Programs/children/Upload/children/DropTarget/DropTarget.tsx
Adds tests, updates colors and hover effects, improves code quality.
> Add button tests and improve styles

- website/frontend/src/common/components/Textarea/Textarea.module.scss
- website/frontend/src/common/components/Textarea/Textarea.test.tsx
- website/frontend/src/common/components/Textarea/Textarea.tsx
- Textarea component with tests
> Add textarea

- .github/workflows/Publish-gear-api.yml
> add npm token for user

- api/package-lock.json
- api/package.json
- api/src/GasSpent.ts
> One more overload of GasSpent methods

- api/package-lock.json
- api/package.json
- api/src/utils/generate.ts
- api/test/GasSpent.test.js
- api/test/GenerateId.test.js
- api/test/ProgramsInteract.test.js
- api/test/SubmitCode.test.js
- api/test/spec/programs/demo_meta.yaml
- api/test/spec/programs/demo_ping.yaml
- api/test/spec/programs/guestbook.yaml
- Generate programId (following https://github.com/gear-tech/gear/pull/769)
- Separate test on GetGasSpent and set 1000 ms timeout
- Test on generate demo_ping programID 
---
> Update generate programId

- api/package-lock.json
- api/package.json
- api/src/Storage.ts
- api/src/default/types-program.json
- api/src/interfaces/program.ts
- Change static_pages type from `u32` to `Compact<u32>`  
[Like here](https://github.com/gear-tech/gear/pull/796/files#diff-d38884f7391ae50f795707dbb281656e8afe38ea3ecac15a6ee80d52724017c0R305) 
---
> Change static_pages type

- utils/gear-ui/package-lock.json
- utils/gear-ui/package.json
- utils/gear-ui/rollup.config.js
- website/frontend/package.json
- yarn.lock
Now you can use `@gear-js/ui` sass modules as easy as `@use '~@gear-js/ui/variables'`
> Move sass modules to root folder

- api/package-lock.json
- api/package.json
- api/test/CreateType.test.js
- api/test/DebugMode.test.js
- api/test/GasSpent.test.js
- api/test/ProgramsInteract.test.js
- api/test/State.test.js
- api/test/SubmitCode.test.js
- api/test/config.js
- Bump @polkadot/api to 7.15.1
- Add config file to test
---
> Bump @polkadot/api to 7.15.1

- .github/workflows/CI-CD-All-dockers-k8s.yml
- .github/workflows/e2e-tests.yaml
> Change data-storage unit-test run

- website/frontend/package.json
- yarn.lock
> Bump @gear-js/api

- website/data-storage/src/consumer/consumer.service.ts
- website/data-storage/src/entities/program.entity.ts
- website/data-storage/src/messages/messages.service.ts
- website/data-storage/src/programs/programs.service.ts
- website/events-listener/src/events.ts
- Listen to `DatabaseWiped` event on events-listener
- Delete db records after DatabaseWiped event
> add: listen to DatabaseWiped event

- website/frontend/src/components/blocks/Header/children/Menu/Menu.module.scss
- website/frontend/src/components/blocks/Header/children/Menu/Menu.tsx
Resolves # .
- Display runtime name and version
> feature: add name, version values on sidebar btn

- api/package-lock.json
- api/package.json
- api/src/State.ts
- api/src/Storage.ts
- api/src/default/types-program.json
- api/src/types/interfaces/program.ts
- api/src/wasm/readState.ts
- api/src/wasm/utils.ts
- api/test/State.test.ts
- Update `ActiveProgram` type
- Update getting pages from storage
- Update tests
---
> Update getting program pages from storage

- website/frontend/src/assets/Icons.tsx
- website/frontend/src/assets/scss/index.scss
- website/frontend/src/components/blocks/Wallet/AccountList/AccountList.scss
- website/frontend/src/components/blocks/Wallet/AccountList/AccountList.tsx
- website/frontend/src/components/blocks/Wallet/SelectAccountModal/SelectAccountModal.module.scss
- website/frontend/src/components/blocks/Wallet/SelectAccountModal/SelectAccountModal.tsx
- website/frontend/src/components/blocks/Wallet/SelectAccountModal/index.ts
- website/frontend/src/components/blocks/Wallet/Wallet.module.scss
- website/frontend/src/components/blocks/Wallet/Wallet.tsx
- website/frontend/src/tests/Header.test.tsx
-Updates the balance value during operations
-Refactor the 'wallet' component
> Update displayed balance

- website/frontend/src/components/blocks/PageHeader/PageHeader.module.scss
- website/frontend/src/components/blocks/PageHeader/PageHeader.tsx
- website/frontend/src/components/pages/Explorer/common/Event/children/LogContent/LogContent.tsx
- website/frontend/src/components/pages/Meta/Meta.tsx
- website/frontend/src/components/pages/Program/Program.module.scss
- website/frontend/src/components/pages/Program/Program.tsx
- website/frontend/src/components/pages/Send/Send.tsx
- website/frontend/src/components/pages/State/State.tsx
- website/frontend/src/hooks/index.ts
- website/frontend/src/hooks/useProgram.ts
- website/frontend/src/services/index.ts
- Changed the logic of receiving program data (message, state, program pages)
> Request metadata without meta wasm

- website/frontend/src/components/common/FormPayload/FormPayload.module.scss
- website/frontend/src/components/common/FormPayload/FormPayload.tsx
- website/frontend/src/components/common/FormPayload/Schema.ts
- website/frontend/src/components/common/FormPayload/helpers.ts
- website/frontend/src/components/common/FormPayload/types.ts
- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/Schema.ts
- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.module.scss
- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/types.ts
- website/frontend/src/components/pages/Send/children/MessageForm/MessageForm.tsx
- website/frontend/src/components/pages/Send/children/MessageForm/types.ts
- website/frontend/src/components/pages/State/State.tsx
- website/frontend/src/components/pages/State/types.ts
- website/frontend/src/consts.ts
- website/frontend/src/helpers.ts
- Add json file upload on payload form
- Refactor payload form logic
> Add json file upload on payload form

- website/frontend/src/components/common/FormPayload/children/EnumItem/EnumItem.tsx
- website/frontend/src/components/common/FormPayload/children/OptionItem/OptionItem.tsx
> Fix payload form logic

- .github/workflows/CI-CD-Prod-k8s.yml
> Sf prod wf

- website/frontend/src/components/common/FormPayload/FormPayload.tsx
- website/frontend/src/tests/FormPayload/FormPayload.test.tsx
- website/frontend/src/tests/FormPayload/inputData.ts
- website/frontend/src/tests/FormPayload/types.ts
-  Add tests for type payload form
> Add tests for type payload form

- website/api-gateway/src/main.ts
- website/frontend/src/consts.ts
> Fix rpc methods

- website/frontend/src/components/blocks/UploadMeta/UploadMeta.tsx
> Fix react error

- website/test-balance/.eslintrc.js
- website/test-balance/package.json
- website/test-balance/src/domain/gear.service.ts
- website/test-balance/src/domain/gear/gear.service.ts
- website/test-balance/src/domain/gear/types.ts
- website/test-balance/src/kafka/kafka.consumer.ts
- website/test-balance/src/main.ts
- yarn.lock
Resolves # .
- Update `transferBalance` in @gear-js/test-balance
- Simple refactor @gear-js/test-balance
-
> Update @gear-js/test-balance with new features @gear-js/api (transfer )

- website/frontend/src/components/pages/Program/children/ProgramInfo/ProgramInfo.tsx
> Fix link path to send message page

- website/frontend/src/components/blocks/UploadMeta/UploadMeta.tsx
- website/frontend/src/components/pages/Meta/children/UploadMetaForm/UploadMetaForm.tsx
> Fix upload meta form

- utils/gear-hooks/package-lock.json
- utils/gear-hooks/package.json
- utils/gear-hooks/src/hooks/api/useReadState.ts
Basic implementation of state reread on any change. Gonna be triggered on every hook execution, so there's a room for improvements.
> Add state changes subscription

- apps/marketplace/Dockerfile
- apps/nft/Dockerfile
> Sf tmp apps

- website/frontend/src/tests/pages/Meta/Meta.test.tsx
> Fix meta test

- website/frontend/src/api/initApi.ts
- website/frontend/src/app/App.tsx
- website/frontend/src/components/AlertTemplate/AlertTemplate.tsx
- website/frontend/src/components/common/CustomLink/CustomLink.module.scss
- website/frontend/src/components/common/CustomLink/CustomLink.tsx
- website/frontend/src/components/common/CustomLink/index.ts
- website/frontend/src/consts.ts
- website/frontend/src/helpers.ts
- website/frontend/src/hooks/index.ts
- website/frontend/src/hooks/useCodeUpload.tsx
- website/frontend/src/hooks/useEventSubscriptions/helpers.tsx
- website/frontend/src/hooks/useEventSubscriptions/index.ts
- website/frontend/src/hooks/useEventSubscriptions/useEventSubscriptions.ts
- website/frontend/src/hooks/useMessageSend.ts
- website/frontend/src/hooks/useProgramUplaod/helpers.ts
- website/frontend/src/hooks/useProgramUplaod/index.ts
- website/frontend/src/hooks/useProgramUplaod/useProgramUpload.tsx
- website/frontend/src/pages/Explorer/children/Block/children/MainTable/Row/Row.tsx
- website/frontend/src/pages/Explorer/children/Events/init.ts
- website/frontend/src/pages/Explorer/common/Event/Event.tsx
- website/frontend/src/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- website/frontend/src/pages/Programs/children/UserProgram/UserProgram.tsx
- website/frontend/src/pages/Send/children/MessageForm/MessageForm.tsx
- website/frontend/src/services/ApiService.ts
- website/frontend/src/tests/mocks/hooks/const.ts
- website/frontend/src/tests/mocks/hooks/hooks.ts
- website/frontend/src/tests/pages/Send/Send.test.tsx
- website/frontend/src/types/explorer.ts
- Refactor subscriptions logic, add subs hook
- Refactor send message, upload program logic (encapsulate logic in a hook)
- Change alert logic
> Refactor subscriptions, send message, upload program logic

- website/frontend/src/components/common/Form/FormPayload/FormPayload.module.scss
- Fixed the payload form style
> Fix form payload style

- website/frontend/src/components/blocks/UploadMeta/UploadMeta.tsx
- website/frontend/src/components/blocks/UploadMeta/helpers.ts
- website/frontend/src/components/blocks/UploadMeta/types.ts
- website/frontend/src/pages/Meta/Meta.tsx
- website/frontend/src/pages/Meta/children/UploadMetaForm/UploadMetaForm.tsx
- website/frontend/src/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- website/frontend/src/tests/pages/Meta/Meta.test.tsx
- Refactored upload meta form logic
- Added reset form logic
- Updated test
> Refactor upload meta form

- website/frontend/src/pages/Explorer/common/Event/children/LogContent/LogContent.tsx
- Fixed decode payload on the explorer page
> Fix payload decode

- website/data-storage/src/code/code.module.ts
- website/data-storage/src/consumer/consumer.module.ts
- website/data-storage/src/consumer/consumer.service.ts
- website/data-storage/src/message/message.service.ts
- website/tests/src/e2e/e2e.test.ts
- website/tests/yarn.lock
> Fix import path in @gear-js/data-storage

- .github/workflows/CI-CD-k8s-gear-apps.yml
- apps/lottery/Dockerfile
> add CI for lottery

- website/frontend/src/hooks/useAccountSubscriptions/helpers.tsx
- Added the  error payload in alert
- Removed useless logic
> Add error message in alert

- api/CHANGELOG.md
- api/README.md
- api/package-lock.json
- api/package.json
- api/src/GearApi.ts
- api/src/Program.ts
- api/src/Storage.ts
- api/src/utils/index.ts
- api/src/utils/prefixes.ts
- api/src/utils/separator.ts
- api/test/Program.test.ts
- api/test/README.md
- Add `api.program.is` method to check whether the address belongs to some program.
---
> Method to check that address belongs to program

- website/frontend/src/components/blocks/Header/Header.module.scss
- website/frontend/src/components/blocks/Header/Header.tsx
- website/frontend/src/components/blocks/Header/children/Menu/Menu.module.scss
- website/frontend/src/components/blocks/Header/children/Menu/Menu.tsx
- website/frontend/src/components/blocks/Header/children/Menu/const.ts
- Added the separator in node info section
- Refactored node info section
> Add the separator in node info section

- api/.eslintrc
- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/Code.ts
- api/src/Program.ts
- api/src/State.ts
- api/src/Storage.ts
- api/src/errors/program.errors.ts
- api/src/types/interfaces/message/entry.ts
- api/src/types/interfaces/program/base.ts
- api/src/types/interfaces/program/code.ts
- api/src/types/interfaces/program/pages.ts
- api/test/State.test.ts
- package.json
- Fix getting program pages according to https://github.com/gear-tech/gear/pull/1193
---
> Read state according to new allocation logic

- website/frontend/src/components/BlocksSummary/BlocksSummary.tsx
- website/frontend/src/hooks/useProgramUplaod/useProgramUpload.tsx
- website/frontend/src/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
- Fixed the submitting logic in upload form
> Fix the upload form

- website/frontend/package.json
- website/frontend/src/assets/images/letter.svg
- website/frontend/src/pages/Mailbox/children/Message/Message.tsx
- website/frontend/src/pages/Message/Message.tsx
- yarn.lock
- Added the link
- Added the error handler in the message page
- Removed an useless style
> Add the "Go to message" link

- website/frontend/src/consts.ts
- website/frontend/src/pages/Mailbox/Mailbox.module.scss
- website/frontend/src/pages/Mailbox/Mailbox.tsx
- website/frontend/src/pages/Mailbox/children/Message/Message.module.scss
- Added the message on the "mailbox" page
> Add "Wallet not connected" message

- .github/workflows/CI-Only-k8s-gear-apps.yml
> Add build apps on CI

- apps/escrow/README.md
> ap-escrow-readme-update

- k8s/staging-env/test-balance/test-balance-workshop-node.yaml
> idea-release

- idea/data-storage/package.json
- idea/events-listener/package.json
- idea/test-balance/package.json
- idea/tests/package.json
- idea/tests/src/prepare/send-message.ts
- idea/tests/src/prepare/upload-collection-code.ts
- idea/tests/src/prepare/upload-programs.ts
- yarn.lock
Resolves # .
- Update `e2e` tests by  #901
> Update `e2e` tests by new version `@gear-js/api`

- apps/lottery/Dockerfile
- apps/marketplace/Dockerfile
- apps/nft/Dockerfile
> add maintainer and update prod

- ansible/tasks/packages/packages.yaml
> add ansible task

- idea/data-storage/src/code/code.repo.ts
> Fix json-rpc method `code.all`

- idea/frontend/package.json
- idea/frontend/src/components/common/Form/FormPayload/PayloadStructure/PayloadStructure.tsx
- idea/frontend/src/components/common/Form/FormPayload/Schema.ts
- idea/frontend/src/components/common/Form/FormPayload/helpers.ts
- idea/frontend/src/components/common/Form/FormPayload/types.ts
- idea/frontend/src/tests/FormPayload/FormPayload.test.tsx
- idea/frontend/src/tests/FormPayload/inputData.ts
- idea/frontend/src/tests/pages/State/State.test.tsx
- yarn.lock
- Added null-type handler to payload form
> Handle null type in payload form

- api/CHANGELOG.md
- api/examples/package-lock.json
- api/examples/src/program/uploadProgram.ts
- api/package-lock.json
- api/package.json
- api/src/Gas.ts
- api/src/default/rpc.json
- api/test/Gas.test.ts
- Add rpc call to calculate gas for create_program extrinsic according to https://github.com/gear-tech/gear/pull/1330
---
> Add calculateInitCreateGas rpc call

- idea/frontend/package.json
- idea/frontend/src/hooks/useGasCalculate/useGasCalculate.ts
- yarn.lock
> Bupm gear-js/api to 0.25.2

- .github/workflows/CI-CD-gear-js-api.yml
- .github/workflows/CI-CD-gear-ui.yml
- .github/workflows/CI-CD-k8s-gear-apps.yml
- .github/workflows/CI-CD-k8s-gear-js.yml
- .github/workflows/CI-CD-meta-cli.yml
- .github/workflows/CI-Only-k8s-gear-apps.yml
> add main branch

- idea/frontend/src/components/blocks/MessageForm/MessageForm.tsx
- idea/frontend/src/components/blocks/MessageForm/helpers.ts
- idea/frontend/src/components/blocks/ProgramForm/ProgramForm.tsx
- idea/frontend/src/components/blocks/ProgramForm/types.ts
- idea/frontend/src/components/common/Form/FormPayload/helpers.ts
- idea/frontend/src/hooks/useProgramActions/types.ts
- idea/frontend/src/hooks/useProgramActions/useProgramActions.tsx
- idea/frontend/src/pages/Main/children/UploadForm/UploadForm.tsx
- Refactored the message form logic
> Refactor the message form logic

- idea/frontend/src/components/blocks/Header/Header.tsx
- idea/frontend/src/components/blocks/Header/children/Menu/Menu.module.scss
- idea/frontend/src/components/blocks/Header/children/Menu/Menu.tsx
- idea/frontend/src/tests/Header.test.tsx
- idea/frontend/src/tests/mocks/hooks/const.ts
> Show node version

- .github/workflows/CI-CD-k8s-gear-apps.yml
- apps/upload-dapp-chain/Dockerfile
- package.json
> add CI/CD for upload-dapp

- .github/workflows/CI-CD-k8s-gear-apps.yml
- apps/supply-chain/Dockerfile
- apps/supply-chain/package.json
- package.json
> add CI/CD for supply-chain

- idea/test-balance/package.json
- idea/test-balance/src/database/app-data-source.ts
- idea/test-balance/src/database/db-create-connection.ts
- idea/test-balance/src/repositories/transfer.repository.ts
- yarn.lock
> Update `@gear-js/test-balance` db connection

- apps/upload-dapp-chain/Dockerfile
- package.json
> Sf change name

- apps/upload-dapp-chain/src/command/command.service.ts
- apps/upload-dapp-chain/src/command/types/index.ts
- apps/upload-dapp-chain/src/common/helpers/get-tg-commands.ts
- apps/upload-dapp-chain/src/common/workflow/workflow.yaml
- apps/upload-dapp-chain/src/dapp-data/dapp-data.repo.ts
- apps/upload-dapp-chain/src/dapp-data/dapp-data.service.ts
- apps/upload-dapp-chain/src/dapp-data/entities/dapp-data.entity.ts
- apps/upload-dapp-chain/src/tgbot/tgbot.controller.ts
- apps/upload-dapp-chain/src/tgbot/tgbot.service.ts
> Update workflow file `@gear-js/upload-dapp-chain`

- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/create-type/TypeInfoReg.ts
- api/src/create-type/index.ts
- api/src/events/Events.ts
- Add method to subscribe to `UserMessageSent` events by actorId
---
> Subscribe to events by actor

- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/Storage.ts
- api/src/default/types-program.json
- api/src/errors/program.errors.ts
- api/src/types/interfaces/program/base.ts
- Add Exited variant to Program enum
---
> Add Exited variant to Program enum

- idea/api-gateway/src/middleware/index.ts
- idea/api-gateway/src/middleware/test-balance.middlware.ts
- idea/api-gateway/src/routes/api-gateway/api-gateway.router.ts
- idea/api-gateway/src/services/api-gateway.service.ts
- yarn.lock
Resolves # .
- Add test balance middleware `@gear-js/api-gateway`
> Add test balance middleware `@gear-js/api-gateway`

- apps/upload-dapp-chain/package.json
- apps/upload-dapp-chain/src/command/command.service.ts
- apps/upload-dapp-chain/src/common/helpers/get-opt-and-meta-wasm.ts
- apps/upload-dapp-chain/src/tgbot/tgbot.service.ts
- yarn.lock
> Fix `upload program` in chain

- apps/upload-dapp-chain/src/command/command.service.ts
- apps/upload-dapp-chain/src/tgbot/tgbot.service.ts
Resolves # .
- Update calculate `gas` in `command service`.
> Update calculate `gas` in `@gear-js/upload-dapp-chain`

- apps/upload-dapp-chain/src/common/workflow/workflow.yaml
> Update yaml `workflow` file 

- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/default/types-program.json
- api/src/types/interfaces/program/base.ts
- api/test/State.test.ts
- Update `ActiveProgram` type according to https://github.com/gear-tech/gear/pull/1474
---
> Update ActiveProgram type

- apps/upload-dapp-chain/src/bot/bot.controller.ts
- apps/upload-dapp-chain/src/bot/bot.service.ts
- apps/upload-dapp-chain/src/common/helpers/get-latest-release-by-repo.ts
- apps/upload-dapp-chain/src/common/helpers/get-tg-commands.ts
- apps/upload-dapp-chain/src/common/helpers/index.ts
- apps/upload-dapp-chain/src/common/helpers/update-wasm-urls-by-last-releases-repo.ts
- apps/upload-dapp-chain/src/common/workflow/workflow.yaml
- apps/upload-dapp-chain/src/tasks/tasks.service.ts
Resolves # .
- Rename bot command from `updateWasmUrlsWorkflow` to `updateWorkflowWasmUrls`
- Update `marketplace` repo in workflow 
> Update `marketplace` repo in workflow

- .github/workflows/CI-CD-k8s-stable.yml
> add wf-stable

- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/default/types-message.json
- api/src/default/types-program.json
- api/src/types/interfaces/gas.ts
- api/src/types/interfaces/program/base.ts
- api/test/programs/Cargo.lock
- Update `ActiveProgram` type according to https://github.com/gear-tech/gear/pull/1505
> Add gas_reservation_map field to ActiveProgram type

- apps/upload-dapp-chain/src/common/helpers/get-account.ts
- apps/upload-dapp-chain/src/common/workflow/workflow.yaml
Resolves # .
- Update account in workflow file
> Update workflow `account`

- idea/data-storage/src/common/helpers/query-builder.ts
> Update sql query search `query builder`

- .github/workflows/CI-CD-k8s-gear-js.yml
- idea/frontend/Dockerfile
> [idea-release] Update CI-CD-k8s-gear-js.yml

- idea/api-gateway/src/common/helpers/send-service-partition.ts
- idea/api-gateway/src/kafka/consumer.ts
- idea/api-gateway/src/kafka/kafka-create-connection.ts
- idea/data-storage/src/gear/gear-event-listener.ts
> Fix ability to set network data partition

- api/CHANGELOG.md
- api/package-lock.json
- api/package.json
- api/src/State.ts
- Increase the value of initial size by 1 when reading the state
---
> Increase the initial size value when reading the state

- apps/social/src/hooks/api.ts
- apps/social/src/types/index.ts
> Fix metaWasm

- .github/workflows/CI-CD-k8s-gear-js.yml
- idea/data-storage/src/rabbitmq/rabbitmq.service.ts
- idea/test-balance/src/rabbitmq/init-rabbitmq.ts
> Update check connection rabbitMQ

- idea/api-gateway/src/rabbitmq/init-rabbitmq.ts
- idea/data-storage/src/rabbitmq/rabbitmq.service.ts
- idea/test-balance/src/rabbitmq/consumer.ts
Resolves # .
- Add consumers parameter `noAck` in services
> Add consumers parameter `noAck` in services

- api/CHANGELOG.md
- api/package.json
- api/src/State.ts
- api/src/metadata/metadata.ts
- api/src/metadata/stateMetadata.ts
- api/src/types/interfaces/metadata.ts
- api/test/Meta.test.ts
- Add variant `option` to TypeKind variants
---
> Add option type

- api/CHANGELOG.md
- api/package.json
- api/src/metadata/is.ts
- api/yarn.lock
- Don't use instanceof to figure out which class an object belongs to
---
> Don't use instanceof to figure out which class an object belongs to

- api/CHANGELOG.md
- api/package.json
- api/src/metadata/metadata.ts
- api/src/types/interfaces/metadata.ts
- api/test/Meta.test.ts
- Add separate type `actorid`
---
> Add separate actorid type

- idea/frontend/package.json
- idea/frontend/src/api/LocalDB.ts
- idea/frontend/src/features/formPayload/helpers/helpers.ts
- idea/frontend/src/features/formPayload/ui/payloadStructure/PayloadStructure.tsx
- idea/frontend/src/features/formPayload/ui/primitiveItem/PrimitiveItem.tsx
- idea/frontend/src/features/uploadMetadata/ui/metadataFileInput/MetadataFileInput.tsx
- idea/frontend/src/pages/state/ui/wasm/Wasm.tsx
- idea/frontend/src/pages/state/ui/wasmStates/WasmStates.tsx
- yarn.lock
- Change meta file input label
- Fix local node meta
- Change file and uploaded functions order
- Fix ActorId field display
- Fix Array field display
> Fix payload fields display and local node meta

- idea/data-storage/src/meta/meta.service.ts
Resolves # .
- Make able to set program name when making request by JSON-RPC method `program.meta.add`
> Make able to set program `name`

- api/CHANGELOG.md
- api/package.json
- api/src/Code.ts
- api/src/errors/program.errors.ts
- api/src/wasm/index.ts
- api/src/wasm/reply.ts
- api/src/wasm/utils.ts
- api/test/Program.test.ts
- Add ability to get metahash by codeId and from wasm
----
> Add ability to get metahash by codeId and directly from wasm

- idea/common/src/enums/program-status.enum.ts
- idea/data-storage/src/common/enums/program-status.enum.ts
- idea/data-storage/src/common/helpers/get-payload-by-gear-event.ts
- idea/data-storage/src/database/migrations/1675420216422-update_program_status.ts
- idea/data-storage/src/gear/gear-event-listener.ts
- idea/data-storage/src/program/types/program-changed.input.ts
Resolves # .
- Update program status `enum`
> Update program status `enum`

- idea/data-storage/src/code/code.service.ts
- idea/data-storage/src/meta/meta.service.ts
- idea/data-storage/src/program/program.service.ts
- idea/data-storage/src/program/types/add-program-meta.input.ts
- idea/data-storage/src/program/types/index.ts
- idea/data-storage/test/meta/meta.service.spec.ts
- idea/data-storage/test/mock/code/code-repository.mock.ts
- idea/data-storage/test/mock/program/program-db.mock.ts
- idea/data-storage/test/mock/program/program-repository.mock.ts
Resolves # .
- Update meta service feature `addMetaByProgram` and refactor `addMetaByCode`.
- Update `meta` service unit tests in `@gear-js/data-storage`
> Update meta service feature `addMetaByProgram`

- idea/common/src/interfaces/meta.ts
- idea/data-storage/package.json
- idea/data-storage/src/code/code.repo.ts
- idea/data-storage/src/code/code.service.ts
- idea/data-storage/src/code/types/code-changed.input.ts
- idea/data-storage/src/code/types/update-code.input.ts
- idea/data-storage/src/common/helpers/get-meta-hash.ts
- idea/data-storage/src/common/helpers/index.ts
- idea/data-storage/src/common/types/gear-api-module.ts
- idea/data-storage/src/common/types/index.ts
- idea/data-storage/src/database/entities/meta.entity.ts
- idea/data-storage/src/gear/gear-event-listener.ts
- idea/data-storage/src/meta/meta.repo.ts
- idea/data-storage/src/meta/meta.service.ts
- idea/tests/package.json
- yarn.lock
Resolves # .
- Update `meta` type in  `@gear-js/common`.
-  Refactor and update `GearEventListener` service.
> Fix code `meta`

- idea/data-storage/src/gear/gear-event-listener.ts
Resolves # .
- Update `handleCodeExtrinsics` in `gear-event-listener` service.
> Fix `handleCodeExtrinsics` in event-listener 

- idea/data-storage/src/common/errors/code.ts
- idea/data-storage/src/common/errors/program.ts
- idea/data-storage/src/database/entities/code.entity.ts
- idea/data-storage/src/database/entities/meta.entity.ts
- idea/data-storage/src/database/migrations/1677069754299-delete_unique_hash_meta_table.ts
- idea/data-storage/src/database/migrations/1677072331302-update_relation_between_code_and_meta.ts
- idea/data-storage/src/gear/gear-event-listener.ts
- idea/data-storage/src/meta/meta.service.ts
- idea/data-storage/test/meta/meta.service.spec.ts
- idea/data-storage/test/mock/metadata/metadata-db.mock.ts
- idea/data-storage/test/mock/metadata/metadata-repository.mock.ts
Resolves # .
- Update `gear-event-listener` in `@gear-js/data-storage`
- Add database migration files to update `code and meta` tables
> Update database relation `code` and `meta`

- tools/cli/README.md
- tools/cli/examples/transactions.yaml
- tools/cli/package.json
- tools/cli/src/app.ts
- tools/cli/src/common/index.ts
- tools/cli/src/common/regex.ts
- tools/cli/src/types/types.ts
- tools/cli/src/workflows/payload.ts
- tools/cli/src/workflows/replace.ts
- tools/cli/src/workflows/run.ts
- tools/cli/src/workflows/validate.ts
- Replace $cli arguments not only in payloads
- Ability to specify node address using CLI argument `--ws`
> Update cli tool

- api/CHANGELOG.md
- api/README.md
- api/programs/Cargo.lock
- api/src/Message.ts
- api/src/Program.ts
- api/src/ResumeSession.ts
- api/src/Storage.ts
- api/src/errors/program.errors.ts
- api/src/events/GearEventData.ts
- api/src/events/GearEvents.ts
- api/src/events/types.ts
- api/src/types/interfaces/ids/program.ts
- api/src/types/interfaces/program/extrinsic.ts
- api/src/types/interfaces/program/pages.ts
- api/test/Code.test.ts
- api/test/DebugMode.test.ts
- api/test/Gas.test.ts
- api/test/Message.test.ts
- api/test/Program.test.ts
- api/test/Waitlist.test.ts
- api/test/utilsFunctions.ts
- Support `resumeSessionInit`, `resumeSessionPush` and `resumeSessionCommit` extrinsics according to https://github.com/gear-tech/gear/pull/2622
> Add resume program extrinsics

- .github/workflows/CI-CD-txwrapper.yml
- api/CHANGELOG.md
- api/programs/Cargo.lock
- api/src/Gas.ts
- api/src/Mailbox.ts
- api/src/Message.ts
- api/src/default/rpc.json
- api/src/default/types-message.json
- api/src/default/types-program.json
- api/src/types/interfaces/events/debug-data-snapshot.ts
- api/src/types/interfaces/message/base.ts
- api/src/types/interfaces/message/details.ts
- api/src/types/interfaces/message/mailbox.ts
- api/src/wasm/importObj.ts
- api/test/Gas.test.ts
- api/test/Message.test.ts
- api/test/utilsFunctions.ts
- Refactor `statusCode` field according to https://github.com/gear-tech/gear/pull/2823.
- Remove `exitCode` argument from `calculateGas.reply` method
- Refactor default types
> Refactor `statusCode` field

- api/CHANGELOG.md
- api/src/GearApi.ts
- api/src/default/rpc.json
- api/test/GearApi.test.ts
- Add `runtime_wasmBlobVersion` rpc call according to https://github.com/gear-tech/gear/pull/2760
> Add `runtime_wasmBlobVersion` rpc call

- api/CHANGELOG.md
- api/package.json
- api/src/metadata/metadata.ts
> Update option regexp to fix meta parsing

- api/CHANGELOG.md
- api/package.json
- api/src/GearApi.ts
- api/src/types/interfaces/gas.ts
- api/test/GearApi.test.ts
> [api] Add `valuePerGas` parameter

- idea/frontend/src/features/gasField/ui/GasField/GasField.tsx
- idea/frontend/src/hooks/useGasMultiplier.ts
- idea/frontend/src/widgets/messageForm/ui/MessageForm.tsx
- idea/frontend/src/widgets/programForm/ui/ProgramForm.tsx
- Fix increase gas button
- Add gas value fallback
> Fix dynamic gas multiplier

- docker-compose.yml
Resolves # .
- add docker-compose file for development
-
-
> add docker-compose for development

- utils/gear-hooks/package.json
- utils/gear-hooks/src/hooks/api/useSendMessage.ts
And add `onInBlock` option callback to `useSendMessage` hook.
> Return message id on successful transaction

- idea/frontend/src/hooks/useProgramActions/types.ts
- idea/frontend/src/hooks/useProgramActions/useProgramActions.tsx
- idea/frontend/src/pages/uploadProgram/ui/UploadProgram.tsx
- idea/frontend/src/widgets/programForm/ui/ProgramForm.tsx
And display it's default value in an input.
> Trim default program name's extension

- .github/workflows/CI-CD-gear-hooks.yml
> fix npm publish

- api/CHANGELOG.md
- api/src/Voucher.ts
- api/src/types/interfaces/voucher.ts
- api/test/Voucher.test.ts
- Add method to get all voucher issued by account
- Improve vouchers query
> Get vouchers issued by account.

- api/CHANGELOG.md
- api/README.md
- api/package.json
- api/src/Voucher.ts
- api/src/events/GearEventData.ts
- api/src/events/GearEvents.ts
- api/src/events/types.ts
- api/src/types/augment/augment-api-tx.ts
- api/test/Voucher.test.ts
- api/test/utilsFunctions.ts
- Add method to decline a voucher according to https://github.com/gear-tech/gear/pull/3725
----
> feat(api): decline voucher

- api/CHANGELOG.md
- api/package.json
- api/src/Voucher.ts
- api/src/types/augment/augment-api-tx.ts
- api/src/types/interfaces/voucher.ts
- api/src/types/lookup.ts
- api/test/Voucher.test.ts
- Add ability to decline voucher using voucher funds
---
> feat(api): voucher call for decline voucher

- .github/workflows/CI-CD-gear-ui.yml
> fixing error with workspaces in  CI-CD-gear-ui.yml

- api/CHANGELOG.md
- api/package.json
- api/src/Blocks.ts
- api/src/Message.ts
- api/src/events/Events.ts
- api/test/Gas.test.ts
- api/test/GearApi.test.ts
- api/test/Message.test.ts
- api/test/Program.test.ts
- api/test/Voucher.test.ts
- api/test/utilsFunctions.ts
- Subscribe to blocks and gear events starting from a particular block
---
> feat(api): subscribe to blocks and events starting from a particular block

- .github/workflows/Update-Voucher-Mainnet.yml
- .github/workflows/Update-Voucher-Testnet.yml
> Sf voucher

- api/CHANGELOG.md
- api/package.json
- api/src/Storage.ts
- api/src/types/lookup.ts
- Update getting program pages according to https://github.com/gear-tech/gear/pull/3791
---
> fix(api): update getting program pages func

- idea/indexer/src/services/message.service.ts
resolves https://github.com/gear-tech/gear-js/issues/1535
> fix(idea/indexer): put messages in the correct order

- idea/frontend/src/features/local-indexer/hooks/use-local-programs.ts
- idea/frontend/src/features/sails/hooks/use-sails.ts
> fix(idea/frontend): local node related code programs

- idea/frontend/src/features/sails/types.ts
- idea/frontend/src/features/sails/ui/fields/primitive-field.tsx
- idea/frontend/src/features/sails/utils/payload/get-default-payload-value.ts
- idea/frontend/src/features/sails/utils/payload/get-payload-schema.ts
- idea/frontend/src/features/sails/utils/payload/get-reset-payload-value.ts
> feat(idea/frontend): display sails payload boolean primitives as a checkbox

- idea/frontend/src/widgets/messageForm/ui/message-form.tsx
- idea/frontend/src/widgets/messageForm/ui/sails-message-form.tsx
- idea/frontend/src/widgets/programForm/ui/ProgramForm.tsx
- idea/frontend/src/widgets/programForm/ui/sails-program-form.tsx
> fix(idea/frontend): rename account existence checkbox

- idea/indexer-db/src/entities/code.entity.ts
- idea/indexer-db/src/entities/event.entity.ts
- idea/indexer-db/src/entities/message-from-program.entity.ts
- idea/indexer-db/src/entities/message-to-program.entity.ts
- idea/indexer-db/src/entities/program.entity.ts
- idea/squid/src/config.ts
- idea/squid/src/event.route.ts
- idea/squid/src/main.ts
- idea/squid/src/temp-state.ts
- idea/squid/tsconfig.json
Resolves #1646 .
- fix type errors with null checks
@osipov-mit
> refactor(idea/squid) change typescript null check config

- api/src/Builtin.ts
- api/src/GearApi.ts
- api/src/errors/builtin.errors.ts
- api/src/errors/index.ts
- api/src/types/augment/augment-api-rpc.ts
Resolves #1654 .
- add class for builtin pallet
@osipov-mit
> feat(api) add support for `builtin` pallet

- idea/squid/src/temp-state.ts
Resolves #1651 .
- remove voucher revoke deletion
@osipov-mit
> fix(idea/squid) some vouchers are not revoked

- idea/explorer/src/services/voucher.ts
- idea/explorer/src/types/requests/voucher.ts
- idea/voucher-indexer/src/service.ts
Resolves #1630 .
- add param for vouchers to get vouchers with empty programs
@osipov-mit
> feat(idea/voucher-indexer) add vouchers issued for all programs param

- api/src/Builtin.ts
- api/test/Builtin.test.ts
Resolves # .
- add test for builtin pallet
- change queryId arguments
@osipov-mit
> feat(api) add missing pallet tests

- idea/frontend/src/features/message/index.ts
- idea/frontend/src/features/message/ui/message-card/message-card.tsx
- idea/frontend/src/features/message/utils.ts
- idea/frontend/src/pages/message/message.tsx
> fix(idea/frontend): hide message name on error

- utils/vara-ui/package-lock.json
- utils/vara-ui/package.json
- utils/vara-ui/src/components/modal/modal.module.scss
- utils/vara-ui/src/components/modal/modal.stories.ts
- utils/vara-ui/src/components/modal/modal.stories.tsx
- utils/vara-ui/src/components/modal/modal.tsx
- utils/vara-ui/src/components/select/select.module.scss
> feat(vara-ui): add Modal `maxWidth` and `headerAddon` props

- idea/gear/squid/Dockerfile
> fix(gear-idea/squid): update Dockerfile

- idea/gear/frontend/package.json
- utils/gear-hooks/package.json
- utils/gear-hooks/src/hooks/sails/use-prepare-program-transaction.ts
- utils/gear-hooks/src/hooks/sails/use-send-program-transaction.ts
- utils/wallet-connect/package.json
- yarn.lock
> fix(hooks): `useSendProgramTransaction` type
