gear-tech/gear-js

api/package-lock.json
api/package.json
api/src/WasmMeta.ts

Fixes # .
- Getting metadata from .meta.wasm if some fileds is not specified 
- Update package version

Fix get wasm metadata

---

api/README.md
api/src/Events.ts
api/src/GearApi.ts

Add getting node info
Using:
```javascript
import { gearApi } from '@gear-js/api';
const gearApi = await GearApi.create();
const chain = await gearApi.chain();
const nodeName = await gearApi.nodeName();
const version = await gearApi.version();
```

Add node info (api)

---

api/README.md
api/src/Events.ts
api/src/Message.ts
api/src/Program.ts

Add subscribing to transfer events only
Use:
```javascript
const unsub = await gearApi.gearEvents.subscribeTransferEvents((event) => {
console.log(event.toHuman());
});
```

Add subscribing to transfer balance events (api)

---

api/api/package-lock.json
api/api/package.json
api/api/src/types/EventData.ts

Fix:
- Remove .at method from @gear-js/api for using library in safari

Remove .at method

---

website/api-gateway/src/api-gateway/api-gateway.service.ts
website/api-gateway/src/interfaces/message.ts
website/data-storage/src/consumer/consumer.controller.ts
website/data-storage/src/consumer/consumer.service.ts
website/data-storage/src/interfaces/message.ts
website/data-storage/src/messages/messages.service.ts

This PR adds JSONRPC method `message.data` to api gateway:
```
$ curl localhost:3000/api --data-binary '{
"jsonrpc": "1.0",
"id": "from-curl",
"method": "message.data",
"params":
{ "genesis": "0x...",
"id": "0x..."
}
}'
```

Add `message.data` RPC method

---

api/README.md
api/jest.config.js
api/package-lock.json
api/package.json
api/src/GearApi.ts
api/src/MessageReply.ts
api/src/Program.ts
api/src/interfaces/transaction.ts
api/src/types/Transaction.ts
api/test/ProgramsInteract.test.js
api/test/checkFunctions.js
api/using-examples/package.json
api/using-examples/src/upload-program.ts

Since `0.11.0` version of @gear-js/api method `signAndSend` will return object of type `Event` like in events subscriptions.
Example how to get messageId with program uploading:
```javascript
api.program.signAndSend(account, ({ events = [], status }) => {
if (status.isFinalized) {
console.log(status.asFinalized); // it returns hash of block, where transaction was added
}
events.forEach(({ event: { method, section, data } }) => {
if (method === 'InitMessageDispatched') {
console.log(data[0]['messageId'].toHuman());
}
});
});
```
@aderrod94 @EugenWay @codev0 @nikitayutanov

Refactor signAndSend method

---

api/README.md
api/package-lock.json
api/package.json
api/src/Blocks.ts
api/test/GearApi.test.js

- Add method to get block number by hash
- Bump version to `0.11.2`
```javascript
const hash = await gearApi.blocks.getBlockNumber(blockHash);
console.log(hash.toNumber());
```

Get block number

---

website/test-balance/src/gear.ts

In fact, it does not due to an apparent bug in an upstream library, but since it crashes and restarts whenever it tries to reconnect, this way will suffice for our needs 🤷

Test Balance now reconnects to the node

---

website/frontend/.eslintrc
website/frontend/package.json
yarn.lock

- Drop husky and lint-staged deps
- Fix eslint `Definition for rule 'react/jsx-filename-extension' was not found` error

Fix eslint file extension error

---

api/package-lock.json
api/package.json
api/src/create-type/generate.ts
api/src/create-type/payload-type-structure.ts
api/src/create-type/utils.ts
api/test/CreateTypeStructure.test.js

- Replace all namespaces instead only one
- Check `Struct` types
- Argument `raw` in `createPayloadTypeStructure` function. 
If it is specified payload structure will  be created without additional fields (type, name, value)
<hr>

Fix create payload structure

---

website/frontend/package.json
website/frontend/src/components/pages/Program/children/MetaData/MetaData.tsx
website/frontend/src/components/pages/Programs/children/Upload/children/UploadForm/UploadForm.tsx
website/frontend/src/components/pages/SendMessage/SendMessage.tsx
website/frontend/src/components/pages/State/State.tsx
yarn.lock

- Bump api to 0.14.4
- Change deprecated functions

Remove deprecated functions for the payload type structure

---

api/package-lock.json
api/package.json
api/src/GearApi.ts
api/src/State.ts
api/src/Storage.ts
api/src/interfaces/gear-api.ts

- Remove `customType` parameter from `GearApiOption` and replace it with `types` 
- `allEvents` variable from `GearApi` class. You can use `gearApi.query.system.events` instead
<hr>

Fix custom type registration

---

utils/gear-ui/package-lock.json
utils/gear-ui/package.json
utils/gear-ui/rollup.config.js
utils/gear-ui/src/components/Button/Button.tsx
utils/gear-ui/src/components/Button/Button.types.ts
utils/gear-ui/src/components/Checkbox/Checkbox.tsx
utils/gear-ui/src/components/Input/Input.tsx
utils/gear-ui/src/components/Modal/Modal.module.scss
utils/gear-ui/src/components/Modal/Modal.test.tsx
utils/gear-ui/src/components/Modal/Modal.tsx
utils/gear-ui/src/components/Radio/Radio.tsx
utils/gear-ui/src/components/Radio/RadioGroup.tsx
utils/gear-ui/src/components/Select/Select.tsx
utils/gear-ui/src/components/Textarea/Textarea.tsx
utils/gear-ui/src/index.ts

- Styles export. Use example:
`import { buttonStyles } from '@gear-js/ui'`
`<button type='button' className={buttonStyles}>text</button>`
- Modal className test
- Modal paddings and min width

Add styles export

---

api/package-lock.json
api/package.json
api/src/GasSpent.ts

- bump @polkadot/api to 8.0.1
- make meta or typeOfPayload optional in gasSpent methods
---

Make meta or typeOfPayload optional in gasSpent methods

---

utils/gear-ui/package-lock.json
utils/gear-ui/package.json
utils/gear-ui/src/components/Button/Button.module.scss
utils/gear-ui/src/components/Button/Button.test.tsx
utils/gear-ui/src/components/Button/Button.tsx
utils/gear-ui/src/components/Button/Button.types.ts

`Button` component now has `display: inline-flex` by default, with the ability to specify `block` prop to take the full width of it's container.

Add block prop to button

---

api/package-lock.json
api/package.json
api/src/default/types-message.json
api/src/events-types/EventData.ts
api/src/types/interfaces/debug.ts
api/src/types/interfaces/message.ts
api/test/DebugMode.test.ts

- Rename `dest` to `destination` in events types
---

Rename `dest` to `destination`

---

website/data-storage/src/consumer/consumer.service.ts
website/data-storage/src/entities/program.entity.ts
website/data-storage/src/metadata/metadata.service.ts
website/data-storage/src/programs/programs.service.ts
website/interfaces/src/api-response.ts

- `program.data` method now does not return the metaFile and other unneccessary fields. So if you need to get a metaFile of a particular program use the `program.meta.get` method.
- Drop `uploadedAt` field from program entity

Optimize requests connected with metadata

---

website/frontend/package.json
yarn.lock

Bump @gear-js/api

---

api/CHANGELOG.md
api/package-lock.json
api/package.json
api/src/Blocks.ts
api/src/Claim.ts
api/src/State.ts
api/src/Storage.ts
api/src/errors/claim.errors.ts
api/src/errors/gear.errors.ts
api/src/errors/index.ts
api/src/errors/state.errors.ts
api/test/State.test.ts

- Throw error while reading the state in case if program does not exist in the storage

Throw error if program doesn't exist in the storage

---

api/CHANGELOG.md
api/README.md
api/package-lock.json
api/package.json
api/src/DebugMode.ts
api/src/GearApi.ts
api/src/events/Events.ts
api/src/events/GearEventData.ts
api/src/events/GearEvents.ts
api/src/types/gear-core/message.ts
api/test/Gas.test.ts
api/test/ProgramsInteract.test.ts
api/test/SubmitCode.test.ts
api/test/Waitlist.test.ts
api/test/testSequencer.js
api/test/utilsFunctions.ts

- Remove events and event data classes
- Add events interfaces

Update events data

---

api/CHANGELOG.md
api/package-lock.json
api/package.json
api/src/Transaction.ts
package.json

- Fix type of `paymentInfo` method's argument.
---

Fix paymentInfo argument type

---

api/CHANGELOG.md
api/package-lock.json
api/package.json
api/src/create-type/generate.ts
api/src/create-type/interfaces.ts
api/src/create-type/payload-type-structure.ts
api/test/CreateTypeStructure.test.ts

- Describe Null type in `createPayloadTypeStructure` function
---

Null is separate type in type structure

---

api/CHANGELOG.md
api/package.json
api/test/Waitlist.test.ts
api/test/programs/Cargo.lock
api/yarn.lock

- Bump `@polkadot/api` to `9.14.1`.
---

Bump @polkadot/api to 9.14.1

---

api/CHANGELOG.md
api/package.json
api/src/Program.ts
api/src/Storage.ts
api/src/errors/program.errors.ts
api/src/utils/create-payload.ts

- Use Bytes as default type, if meta or type wasn't specified.
- Handle error in `program.metaHex` method
---

Use Bytes as default type, if meta or type wasn't specified. 

---

idea/common/src/interfaces/rpc-request/indexer.ts
idea/frontend/src/widgets/programMessages/ui/ProgramMessages.tsx
idea/indexer/src/gear/indexer.ts
idea/indexer/src/services/message.service.ts
idea/tests/e2e/indexer.test.ts

- `query` parameter has been removed from `message.all` request. It will significantly reduce the request time.
- The `source` and `destination parameters can be used to request all program messages.

[gear-idea] Reduce the speed of program messages requests

---

utils/gear-hooks/package.json
utils/gear-hooks/src/hooks/api/index.ts
utils/gear-hooks/src/hooks/api/useCalculateGas/index.ts
utils/gear-hooks/src/hooks/api/useCalculateGas/types.ts
utils/gear-hooks/src/hooks/api/useDepricatedSendMessage.ts
utils/gear-hooks/src/hooks/api/useSendMessage.ts
utils/gear-hooks/src/hooks/index.ts
utils/gear-hooks/src/index.ts

Drop `useSendMessage` gas calculation.
From now on, `sendMessage` callback requires `gasLimit` option, which can be obtained with help of `useHandleCalculateGas` hook.
`useDepricatedSendMessage` hook is still there to support old applications, but in the near future it'll be removed.

Add useSendMessage gas limit

---

utils/gear-hooks/package.json
utils/gear-hooks/rollup.config.js
utils/gear-hooks/src/context/Account.tsx
utils/gear-hooks/src/context/Api.tsx
utils/gear-hooks/src/hooks/api/balance/use-balance-format.ts
utils/gear-hooks/src/hooks/api/useCalculateGas/index.ts
utils/gear-hooks/src/hooks/api/useDepricatedSendMessage.ts
utils/gear-hooks/src/hooks/api/useProgram/index.ts
utils/gear-hooks/src/hooks/api/useProgram/types.ts
utils/gear-hooks/src/hooks/api/useProgram/useHandlers/useHandleSignStatus.ts
utils/gear-hooks/src/hooks/api/useSendMessage.ts
utils/gear-hooks/yarn.lock
yarn.lock

Expand `useApi` hook to support light client connection and smooth network change without forced page reload.
`api` is more type safe now - it's `undefined` before initialization. Use `isApiReady` variable to validate it's current state.

[hooks] Add light client

---

api/CHANGELOG.md
api/README.md
api/package.json
api/programs/Cargo.lock
api/programs/rust-toolchain.toml
api/src/GearApi.ts
api/src/Message.ts
api/src/Program.ts
api/src/Voucher.ts
api/src/apis/index.ts
api/src/apis/vara-testnet/api.ts
api/src/apis/vara/api.ts
api/src/apis/vara/message.ts
api/src/apis/vara/program.ts
api/src/index.ts
api/src/types/augment/augment-api-tx.ts
api/src/types/interfaces/index.ts
api/src/types/interfaces/message/extrinsic.ts
api/src/types/interfaces/program/extrinsic.ts
api/src/types/interfaces/voucher.ts
api/src/types/lookup.ts
api/src/utils/getExtrinsic.ts
api/src/utils/index.ts
api/test/ExtrinsicError.test.ts
api/test/Message.test.ts
api/test/Transfer.test.ts
api/test/Voucher.test.ts

- Support `gearVoucher.call` extrinsic according to https://github.com/gear-tech/gear/pull/3401
- Support `keepAlive` field in `sendMessage`, `sendReply`, `uploadProgram` and `createProgram` extrinsics accoriding to https://github.com/gear-tech/gear/pull/3425
- Bump `polkadot-js` version to 10.10.1
---

Support `gearVoucher.call` tx and keepAlive parameter in gear txs

---

.github/workflows/CI-CD-gear-js-api.yml
api/CHANGELOG.md
api/src/GearApi.ts
api/src/types/interfaces/extrinsic-failed.ts
api/src/types/interfaces/index.ts
api/test/ExtrinsicError.test.ts

- Fix `api.getExtrinsicFailedError` method. It now returns an object with the formatted docs, method and name of the error

Fix `api.getExtrinsicFailed` method

---

api/.gitignore
api/CHANGELOG.md
api/README.md
api/package.json
api/programs/Cargo.lock
api/programs/Cargo.toml
api/programs/empty/Cargo.toml
api/programs/empty/build.rs
api/programs/empty/src/lib.rs
api/src/Code.ts
api/src/Message.ts
api/src/Voucher.ts
api/src/types/augment/augment-api-errors.ts
api/src/types/augment/augment-api-tx.ts
api/src/types/interfaces/program/code.ts
api/src/types/interfaces/program/index.ts
api/src/types/interfaces/voucher.ts
api/src/types/lookup.ts
api/test/Voucher.test.ts

- Support `uploadCode` call for vouchers according  to https://github.com/gear-tech/gear/pull/3672

Support `upload_code` for vouchers

---

api/CHANGELOG.md
api/package.json
api/src/Storage.ts
api/src/Voucher.ts
api/src/consts.ts

https://github.com/gear-tech/gear-js/pull/1447
- Read storage of memory pages.
https://github.com/gear-tech/gear-js/pull/1451
<i><b>Breaking changes</b></i>
- Fix `api.getExtrinsicFailedError` method. It now returns an object with the formatted docs, method and name of the error
https://github.com/gear-tech/gear-js/pull/1467
- Support new vouchers.
- Bump polkadot dependencies to `10.11.2`
https://github.com/gear-tech/gear-js/pull/1472
- Support `uploadCode` call for vouchers.

[api] Release `0.36.0`

---

utils/gear-hooks/package.json
utils/gear-hooks/src/hooks/api/balance/use-balance-format.ts
utils/gear-hooks/src/hooks/handlers/index.ts
utils/gear-hooks/src/hooks/handlers/use-send-message-handler.ts
utils/gear-hooks/src/hooks/index.ts
utils/gear-hooks/src/index.ts
utils/gear-hooks/src/utils/index.ts

- Rename `useSendMessageHandler` to `useSendMessageWithGas`, fix extra gas calculation for `waited` message, export types
- Add `gasMultiplier` parameter
- Add `BigNumber` lib export

Fix `waited` message extra gas calculation, add `gasMultiplier` parameter

---

api/CHANGELOG.md
api/package.json
api/src/events/Events.ts

- Subscribe to gear events only on finalized blocks
---

feat(api): subscribe to events only on finalized blocks

---

api/CHANGELOG.md
api/package.json
api/src/Balance.ts
api/yarn.lock

- Remove `balances.transfer` method
- `api.balance.transfer` method now accepts one more argument `keepAlive` that is set to `true` by default
---

fix(api): remove `balances.transfer` method

---

idea/frontend/src/api/program/requests.ts
idea/frontend/src/hooks/use-contract-api-with-file.ts
idea/frontend/src/hooks/use-sign-and-send.tsx
idea/frontend/src/hooks/useCodeUpload/types.ts
idea/frontend/src/hooks/useCodeUpload/useCodeUpload.tsx
idea/frontend/src/hooks/useProgramActions/consts.ts
idea/frontend/src/hooks/useProgramActions/types.ts
idea/frontend/src/hooks/useProgramActions/useProgramActions.tsx
idea/frontend/src/pages/initializeProgram/ui/InitializeProgram.tsx
idea/frontend/src/pages/uploadProgram/ui/UploadProgram.tsx
idea/frontend/src/widgets/uploadMetadataModal/ui/UploadMetadataModal.tsx

Necessary improvements in order to start refactoring storage for local nodes.
Re-using `useSignAndSend` hook to drop repetitive logic and separate upload metadata side-effects.

refactor(idea/frontend): upload program/code `signAndSend`

---

idea/squid/src/call.route.ts
idea/squid/src/event.route.ts
idea/squid/src/main.ts
idea/squid/src/temp-state.ts

Resolves # .
- move handler functionality to router for handling event and subrouter for handling calls
- correct typo
-
@osipov-mit

refactor(squid) split state handler into routers

---

idea/gear/frontend/package.json
package.json
utils/gear-ui/package.json
utils/vara-ui/package.json
utils/vara-ui/vite.config.ts
utils/wallet-connect/package.json
utils/wallet-connect/vite.config.ts
yarn.lock

chore(vara-ui): bump `vite`
